/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SignInApp;

/**
 *
 * @author Jason
 */
public class AddClassPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddClassPanel
     */
    String class1;
    String class2;
    String class3;
    
    public AddClassPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classCode1 = new javax.swing.JTextField();
        classCode2 = new javax.swing.JTextField();
        classCode3 = new javax.swing.JTextField();

        classCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classCode1ActionPerformed(evt);
            }
        });

        classCode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classCode2ActionPerformed(evt);
            }
        });

        classCode3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classCode3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(classCode1)
                    .addComponent(classCode2)
                    .addComponent(classCode3, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(classCode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(classCode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(classCode3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void classCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classCode1ActionPerformed
        // TODO add your handling code here:
        class1= classCode1.getText();
    }//GEN-LAST:event_classCode1ActionPerformed

    private void classCode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classCode2ActionPerformed
        // TODO add your handling code here:
        class2 = classCode2.getText();
    }//GEN-LAST:event_classCode2ActionPerformed

    private void classCode3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classCode3ActionPerformed
        // TODO add your handling code here:
        class3 = classCode3.getText();
    }//GEN-LAST:event_classCode3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField classCode1;
    private javax.swing.JTextField classCode2;
    private javax.swing.JTextField classCode3;
    // End of variables declaration//GEN-END:variables
}
